print()
n = input("Name: ")
a = int(input("Age: "))
c = input("Course: ")
y = int(input("Year: "))
p = input("Present Address: ")
pa = input("Permanent Address: ")
print("Student Details")
print("Name: ", n)
print("Age: ", a)
print("Course: ", c)
print("Year: ", y)
print("Present Address: ",p)
print("Permanent Address: ", pa)
print()